-- Oracle 19c+ schema for crawler state and complete output artifacts.
-- For Oracle 21c/23ai, CLOB columns constrained with IS JSON may be changed
-- to the native JSON data type.

CREATE TABLE crawl_jobs (
    job_id              VARCHAR2(36 CHAR) PRIMARY KEY,
    plugin              VARCHAR2(100 CHAR) NOT NULL,
    status              VARCHAR2(40 CHAR) NOT NULL,
    stop_requested      NUMBER(1) DEFAULT 0 NOT NULL,
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL,
    started_at          TIMESTAMP WITH TIME ZONE,
    finished_at         TIMESTAMP WITH TIME ZONE,
    CONSTRAINT ck_job_stop CHECK (stop_requested IN (0, 1))
);

CREATE INDEX ix_jobs_status ON crawl_jobs(status, created_at);

CREATE TABLE crawl_items (
    job_id                  VARCHAR2(36 CHAR) NOT NULL,
    item_id                 VARCHAR2(64 CHAR) NOT NULL,
    source_url              VARCHAR2(2048 CHAR) NOT NULL,
    canonical_url           VARCHAR2(2048 CHAR) NOT NULL,
    canonical_url_hash      VARCHAR2(64 CHAR) NOT NULL,
    title                   VARCHAR2(1000 CHAR),
    discovery_page          VARCHAR2(2048 CHAR),
    status                  VARCHAR2(40 CHAR) NOT NULL,
    attempt_count           NUMBER(10) DEFAULT 0 NOT NULL,
    content_hash            VARCHAR2(64 CHAR),
    previous_content_hash   VARCHAR2(64 CHAR),
    snapshot_hash           VARCHAR2(64 CHAR),
    previous_snapshot_hash  VARCHAR2(64 CHAR),
    baseline_job_id         VARCHAR2(36 CHAR),
    change_status           VARCHAR2(30 CHAR),
    changed_components_json CLOB,
    last_error_code         VARCHAR2(100 CHAR),
    artifact_dir            VARCHAR2(2048 CHAR),
    checked_at              TIMESTAMP WITH TIME ZONE,
    updated_at              TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT pk_crawl_items PRIMARY KEY (job_id, item_id),
    CONSTRAINT fk_items_job FOREIGN KEY (job_id)
        REFERENCES crawl_jobs(job_id) ON DELETE CASCADE,
    CONSTRAINT ck_items_changed_json CHECK (
        changed_components_json IS JSON
    )
);

CREATE INDEX ix_items_status ON crawl_items(job_id, status);
CREATE INDEX ix_items_url_hash ON crawl_items(canonical_url_hash);
CREATE INDEX ix_items_baseline ON crawl_items(item_id, change_status, updated_at);

-- One immutable parsed snapshot for one item in one job. document_json is the
-- lossless source of truth; the child tables below are queryable projections.
CREATE TABLE disease_documents (
    doc_pk              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id              VARCHAR2(36 CHAR) NOT NULL,
    item_id             VARCHAR2(64 CHAR) NOT NULL,
    document_id         VARCHAR2(64 CHAR) NOT NULL,
    schema_version      VARCHAR2(20 CHAR) NOT NULL,
    disease_name        VARCHAR2(1000 CHAR) NOT NULL,
    summary             CLOB,
    prognosis           CLOB,
    source_plugin       VARCHAR2(100 CHAR) NOT NULL,
    source_url          VARCHAR2(2048 CHAR) NOT NULL,
    canonical_url       VARCHAR2(2048 CHAR) NOT NULL,
    language_code       VARCHAR2(16 CHAR) NOT NULL,
    retrieved_at        TIMESTAMP WITH TIME ZONE NOT NULL,
    content_hash        VARCHAR2(64 CHAR) NOT NULL,
    parse_method        VARCHAR2(20 CHAR) NOT NULL,
    model_id            VARCHAR2(200 CHAR),
    prompt_version      VARCHAR2(100 CHAR),
    parser_version      VARCHAR2(100 CHAR) NOT NULL,
    confidence          NUMBER(7,6),
    parse_warnings_json CLOB,
    document_json       CLOB NOT NULL,
    created_at          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT uq_doc_job_item UNIQUE (job_id, item_id),
    CONSTRAINT fk_doc_item FOREIGN KEY (job_id, item_id)
        REFERENCES crawl_items(job_id, item_id) ON DELETE CASCADE,
    CONSTRAINT ck_doc_confidence CHECK (
        confidence IS NULL OR confidence BETWEEN 0 AND 1
    ),
    CONSTRAINT ck_doc_warnings_json CHECK (parse_warnings_json IS JSON),
    CONSTRAINT ck_document_json CHECK (document_json IS JSON)
);

CREATE INDEX ix_doc_document_id ON disease_documents(document_id);
CREATE INDEX ix_doc_name ON disease_documents(disease_name);
CREATE INDEX ix_doc_content_hash ON disease_documents(content_hash);

-- Ordered multi-value fields from disease.json. FIELD_NAME values represent
-- aliases, causes, risk_factors, symptoms, diagnosis, treatment, prevention,
-- and when_to_seek_care.
CREATE TABLE disease_field_values (
    value_pk            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_pk              NUMBER NOT NULL,
    field_name          VARCHAR2(40 CHAR) NOT NULL,
    value_order         NUMBER(10) NOT NULL,
    field_value         CLOB NOT NULL,
    CONSTRAINT fk_field_doc FOREIGN KEY (doc_pk)
        REFERENCES disease_documents(doc_pk) ON DELETE CASCADE,
    CONSTRAINT uq_field_order UNIQUE (doc_pk, field_name, value_order),
    CONSTRAINT ck_field_name CHECK (field_name IN (
        'aliases', 'causes', 'risk_factors', 'symptoms', 'diagnosis',
        'treatment', 'prevention', 'when_to_seek_care'
    )),
    CONSTRAINT ck_field_order CHECK (value_order >= 1)
);

CREATE INDEX ix_field_doc_name ON disease_field_values(doc_pk, field_name);

CREATE TABLE disease_sections (
    section_pk          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_pk              NUMBER NOT NULL,
    section_order       NUMBER(10) NOT NULL,
    heading             VARCHAR2(1000 CHAR) NOT NULL,
    heading_level       NUMBER(1) NOT NULL,
    markdown            CLOB NOT NULL,
    CONSTRAINT fk_section_doc FOREIGN KEY (doc_pk)
        REFERENCES disease_documents(doc_pk) ON DELETE CASCADE,
    CONSTRAINT uq_section_order UNIQUE (doc_pk, section_order),
    CONSTRAINT ck_heading_level CHECK (heading_level BETWEEN 1 AND 6)
);

CREATE TABLE disease_menu_nodes (
    menu_node_pk        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_pk              NUMBER NOT NULL,
    node_level          NUMBER(10) NOT NULL,
    distance_from_item  NUMBER(10) NOT NULL,
    label               VARCHAR2(1000 CHAR) NOT NULL,
    node_url            VARCHAR2(2048 CHAR),
    is_current          NUMBER(1) DEFAULT 0 NOT NULL,
    CONSTRAINT fk_menu_doc FOREIGN KEY (doc_pk)
        REFERENCES disease_documents(doc_pk) ON DELETE CASCADE,
    CONSTRAINT uq_menu_level UNIQUE (doc_pk, node_level),
    CONSTRAINT ck_menu_level CHECK (node_level >= 0),
    CONSTRAINT ck_menu_distance CHECK (distance_from_item >= 0),
    CONSTRAINT ck_menu_current CHECK (is_current IN (0, 1))
);

CREATE TABLE disease_tabs (
    tab_pk              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    doc_pk              NUMBER NOT NULL,
    tab_key             VARCHAR2(20 CHAR) NOT NULL,
    label               VARCHAR2(200 CHAR) NOT NULL,
    source_url          VARCHAR2(2048 CHAR) NOT NULL,
    is_available        NUMBER(1) DEFAULT 1 NOT NULL,
    plain_text          CLOB,
    markdown            CLOB,
    content_hash        VARCHAR2(64 CHAR),
    headers_json        CLOB,
    warnings_json       CLOB,
    CONSTRAINT fk_tab_doc FOREIGN KEY (doc_pk)
        REFERENCES disease_documents(doc_pk) ON DELETE CASCADE,
    CONSTRAINT uq_doc_tab UNIQUE (doc_pk, tab_key),
    CONSTRAINT ck_tab_key CHECK (
        tab_key IN ('info', 'life_dd_tpd', 'ip', 'health')
    ),
    CONSTRAINT ck_tab_available CHECK (is_available IN (0, 1)),
    CONSTRAINT ck_tab_headers_json CHECK (headers_json IS JSON),
    CONSTRAINT ck_tab_warnings_json CHECK (warnings_json IS JSON)
);

CREATE TABLE tab_tables (
    table_pk            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tab_pk              NUMBER NOT NULL,
    table_order         NUMBER(10) NOT NULL,
    rows_json           CLOB NOT NULL,
    CONSTRAINT fk_table_tab FOREIGN KEY (tab_pk)
        REFERENCES disease_tabs(tab_pk) ON DELETE CASCADE,
    CONSTRAINT uq_tab_table_order UNIQUE (tab_pk, table_order),
    CONSTRAINT ck_table_rows_json CHECK (rows_json IS JSON)
);

CREATE TABLE tab_related_details (
    detail_pk           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tab_pk              NUMBER NOT NULL,
    detail_order        NUMBER(10) NOT NULL,
    label               VARCHAR2(1000 CHAR) NOT NULL,
    detail_url          VARCHAR2(2048 CHAR) NOT NULL,
    is_available        NUMBER(1) DEFAULT 1 NOT NULL,
    plain_text          CLOB,
    markdown            CLOB,
    content_hash        VARCHAR2(64 CHAR),
    warnings_json       CLOB,
    CONSTRAINT fk_detail_tab FOREIGN KEY (tab_pk)
        REFERENCES disease_tabs(tab_pk) ON DELETE CASCADE,
    CONSTRAINT uq_tab_detail_order UNIQUE (tab_pk, detail_order),
    CONSTRAINT ck_detail_available CHECK (is_available IN (0, 1)),
    CONSTRAINT ck_detail_warnings_json CHECK (warnings_json IS JSON)
);

-- Flat rows are canonical. The tree can always be reconstructed by
-- classification_id, parent_classification_id, node_level, and row_order.
CREATE TABLE classifications (
    class_row_pk            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tab_pk                  NUMBER NOT NULL,
    row_order               NUMBER(10) NOT NULL,
    classification_id       VARCHAR2(64 CHAR) NOT NULL,
    parent_classification_id VARCHAR2(64 CHAR),
    parent_classification   VARCHAR2(1000 CHAR),
    classification_name     VARCHAR2(1000 CHAR) NOT NULL,
    node_level              NUMBER(10) NOT NULL,
    is_group                NUMBER(1) NOT NULL,
    class_code              VARCHAR2(200 CHAR),
    path_json               CLOB NOT NULL,
    raw_cells_json          CLOB,
    CONSTRAINT fk_class_tab FOREIGN KEY (tab_pk)
        REFERENCES disease_tabs(tab_pk) ON DELETE CASCADE,
    CONSTRAINT uq_class_row UNIQUE (tab_pk, row_order),
    CONSTRAINT ck_class_level CHECK (node_level >= 0),
    CONSTRAINT ck_class_group CHECK (is_group IN (0, 1)),
    CONSTRAINT ck_class_path_json CHECK (path_json IS JSON),
    CONSTRAINT ck_class_cells_json CHECK (raw_cells_json IS JSON)
);

CREATE INDEX ix_class_identity ON classifications(tab_pk, classification_id);
CREATE INDEX ix_class_parent ON classifications(tab_pk, parent_classification_id);
CREATE INDEX ix_class_level ON classifications(tab_pk, node_level, row_order);

CREATE TABLE classification_ratings (
    rating_pk           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class_row_pk        NUMBER NOT NULL,
    rating_name         VARCHAR2(200 CHAR) NOT NULL,
    rating_value        VARCHAR2(1000 CHAR),
    rating_order        NUMBER(10) NOT NULL,
    CONSTRAINT fk_rating_class FOREIGN KEY (class_row_pk)
        REFERENCES classifications(class_row_pk) ON DELETE CASCADE,
    CONSTRAINT uq_class_rating UNIQUE (class_row_pk, rating_name),
    CONSTRAINT uq_rating_order UNIQUE (class_row_pk, rating_order)
);

CREATE TABLE item_coverage (
    coverage_pk         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id              VARCHAR2(36 CHAR) NOT NULL,
    item_id             VARCHAR2(64 CHAR) NOT NULL,
    schema_version      VARCHAR2(20 CHAR) NOT NULL,
    is_complete         NUMBER(1) NOT NULL,
    checked_at          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    coverage_json       CLOB NOT NULL,
    CONSTRAINT uq_coverage_item UNIQUE (job_id, item_id),
    CONSTRAINT fk_coverage_item FOREIGN KEY (job_id, item_id)
        REFERENCES crawl_items(job_id, item_id) ON DELETE CASCADE,
    CONSTRAINT ck_coverage_complete CHECK (is_complete IN (0, 1)),
    CONSTRAINT ck_coverage_json CHECK (coverage_json IS JSON)
);

CREATE TABLE coverage_checks (
    coverage_pk         NUMBER NOT NULL,
    check_name          VARCHAR2(100 CHAR) NOT NULL,
    passed              NUMBER(1) NOT NULL,
    CONSTRAINT pk_coverage_checks PRIMARY KEY (coverage_pk, check_name),
    CONSTRAINT fk_check_coverage FOREIGN KEY (coverage_pk)
        REFERENCES item_coverage(coverage_pk) ON DELETE CASCADE,
    CONSTRAINT ck_check_passed CHECK (passed IN (0, 1))
);

CREATE TABLE coverage_messages (
    message_pk          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    coverage_pk         NUMBER NOT NULL,
    message_type        VARCHAR2(10 CHAR) NOT NULL,
    message_order       NUMBER(10) NOT NULL,
    message_code        VARCHAR2(1000 CHAR) NOT NULL,
    CONSTRAINT fk_message_coverage FOREIGN KEY (coverage_pk)
        REFERENCES item_coverage(coverage_pk) ON DELETE CASCADE,
    CONSTRAINT uq_coverage_message UNIQUE (
        coverage_pk, message_type, message_order
    ),
    CONSTRAINT ck_message_type CHECK (
        message_type IN ('blocker', 'warning')
    )
);

-- Stores item-level files (raw.html, tabs.json, disease.json, screenshot.png,
-- etc.) and job-level files (report.json, site-profile.json, coverage-report.json).
CREATE TABLE output_artifacts (
    artifact_pk         NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_id              VARCHAR2(36 CHAR) NOT NULL,
    item_id             VARCHAR2(64 CHAR),
    item_scope          GENERATED ALWAYS AS (NVL(item_id, '@job')) VIRTUAL,
    artifact_name       VARCHAR2(100 CHAR) NOT NULL,
    file_name           VARCHAR2(255 CHAR) NOT NULL,
    media_type          VARCHAR2(255 CHAR) NOT NULL,
    sha256              VARCHAR2(64 CHAR) NOT NULL,
    byte_size           NUMBER(19) NOT NULL,
    text_content        CLOB,
    binary_content      BLOB,
    created_at          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_artifact_job FOREIGN KEY (job_id)
        REFERENCES crawl_jobs(job_id) ON DELETE CASCADE,
    CONSTRAINT fk_artifact_item FOREIGN KEY (job_id, item_id)
        REFERENCES crawl_items(job_id, item_id) ON DELETE CASCADE,
    CONSTRAINT uq_artifact UNIQUE (job_id, item_scope, artifact_name),
    CONSTRAINT ck_artifact_size CHECK (byte_size >= 0),
    CONSTRAINT ck_artifact_payload CHECK (
        (text_content IS NOT NULL AND binary_content IS NULL)
        OR (text_content IS NULL AND binary_content IS NOT NULL)
    )
);

CREATE INDEX ix_artifact_item ON output_artifacts(job_id, item_id);
CREATE INDEX ix_artifact_sha ON output_artifacts(sha256);

COMMENT ON TABLE disease_documents IS
    'Lossless disease.json plus queryable scalar projection per job item';
COMMENT ON TABLE classifications IS
    'Life/DD/TPD, IP and Health hierarchy rows in original display order';
COMMENT ON TABLE output_artifacts IS
    'Complete text and binary crawler outputs, including screenshots';
