from enum import StrEnum


class ErrorCode(StrEnum):
    AUTH_INVALID_CREDENTIALS = "AUTH_INVALID_CREDENTIALS"
    AUTH_SESSION_EXPIRED = "AUTH_SESSION_EXPIRED"
    AUTH_FORM_NOT_FOUND = "AUTH_FORM_NOT_FOUND"
    AUTH_MFA_OR_CAPTCHA = "AUTH_MFA_OR_CAPTCHA"
    NETWORK_TIMEOUT = "NETWORK_TIMEOUT"
    NAVIGATION_FAILED = "NAVIGATION_FAILED"
    PAGE_TYPE_UNKNOWN = "PAGE_TYPE_UNKNOWN"
    NAVIGATION_LOOP_EXHAUSTED = "NAVIGATION_LOOP_EXHAUSTED"
    SELECTOR_NOT_FOUND = "SELECTOR_NOT_FOUND"
    CONTENT_EMPTY = "CONTENT_EMPTY"
    CONTENT_INVALID = "CONTENT_INVALID"
    SITE_PROFILE_INCOMPLETE = "SITE_PROFILE_INCOMPLETE"
    COVERAGE_INCOMPLETE = "COVERAGE_INCOMPLETE"
    LLM_OUTPUT_INVALID = "LLM_OUTPUT_INVALID"
    GEMINI_AUTH_FAILED = "GEMINI_AUTH_FAILED"
    GEMINI_RATE_LIMITED = "GEMINI_RATE_LIMITED"
    GEMINI_TIMEOUT = "GEMINI_TIMEOUT"
    GEMINI_UNAVAILABLE = "GEMINI_UNAVAILABLE"
    GEMINI_OUTPUT_INVALID = "GEMINI_OUTPUT_INVALID"
    AGENT_ACTION_INVALID = "AGENT_ACTION_INVALID"
    AGENT_BUDGET_EXHAUSTED = "AGENT_BUDGET_EXHAUSTED"
    DISEASE_NOT_CONFIRMED = "DISEASE_NOT_CONFIRMED"
    UNSAFE_CONTENT_PAYLOAD = "UNSAFE_CONTENT_PAYLOAD"
    GROUNDING_FAILED = "GROUNDING_FAILED"
    NORMALIZATION_CONFLICT = "NORMALIZATION_CONFLICT"
    PARSE_TIMEOUT = "PARSE_TIMEOUT"
    BROWSER_UNAVAILABLE = "BROWSER_UNAVAILABLE"
    SESSION_STATE_INVALID = "SESSION_STATE_INVALID"
    STORAGE_WRITE = "STORAGE_WRITE"
    UNEXPECTED = "UNEXPECTED"


class CrawlerError(Exception):
    def __init__(self, code: ErrorCode, message: str) -> None:
        super().__init__(message)
        self.code = code
